# Generated by Django 5.0.4 on 2024-04-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceShape', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairName', models.CharField(max_length=100)),
                ('face_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_hairstyle', to='hairsystem.faceshape')),
            ],
        ),
    ]
